spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: true
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist
mybatis:
  mapper-locations: classpath:mybatis/mapper/*xml
security:
  jwt:
    secret: a3NmamtsZHNmamtkZmllb3BhZHNmbGRKS0xKOkxLO2xka3Bld2VvcWU=
    access: 1
    refresh: 30
springdoc:
  override-with-generic-response: false

