spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: true
#      data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: a3NmamtsZHNmamtkZmllb3BhZHNmbGRKS0xKOkxLO2xka3Bld2VvcWU=
    access: 1
    refresh: 30

